stages: 
  - build
  - test

include:
  - gitlab/base-line.yml

.dev:
  extends:
    - .base-line
build-job:
  stage: build
  extends:
    - .dev
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test-job:
  stage: test
  extends:
    - .dev
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

